### ISSUE TITLE
Wheel slider bug

### ISSUE THREAD

**Issue by bartekjacak** [claviska/jquery-minicolors#167]
In wheel color picker's slider you can't pick 'the highest' color, because the slider isn't height enough. For example, if you type `#ffffff` value, change the value using slider, and try to pick `#ffffff` color again you can't, because the `#fafbff` color is on the top.

**Comment by claviska** [comment]
Odd, probably a rounding error. Thanks for reporting.

**Comment by claviska** [comment]
The reason you were seeing that value is because the selection wasn't in the exact center of the wheel. Admittedly, it's a bit tedious to get to that one spot, but you can get to it:

![screen shot 2017-01-14 at 11 37 05 am](https://cloud.githubusercontent.com/assets/55639/21956402/d15c5198-da4d-11e6-99f6-587bae375759.png)
