### ISSUE TITLE
Feature request : hex format  without  #

### ISSUE THREAD

**Issue by chrispcb** [claviska/jquery-minicolors#200]
to simplify user input, by copy & past for exemple, # is useless like color box on photoshop.

Is possible to add a option to get a hex format  without  # ?

I changed 3 code line : 

```
value = convertCase( value, settings.letterCase ).replace('#', '');
if( !preserveInputValue ) input.val(value.replace('#', ''));
input.val( convertCase(input.val(), settings.letterCase).replace('#', '') );
```

**Comment by claviska** [comment]
Good point. For hex format, I'd rather see an input mask instead of another format to support. So if you didn't have the # it would be added, or if you try to delete it, for example, it would still remain.

**Comment by chrispcb** [comment]
Indeed, this is another point of view that better respects the syntax format.

**Comment by claviska** [comment]
My analysis of this issue:

- Entering a hex color by typing or via copy/paste works fine with and without `#`. If the symbol is missing, it will be added automatically to form a proper hex color string.
- Getting the hex value of a control will always produce a hex color string starting with `#`.

Given that, the desire to omit the `#` symbol in the input is purely aesthetic. Since it's technically not a valid hex string — and omitting it while typing or copying/pasting doesn't affect anything — I'd prefer to leave the behavior as-is.
