### ISSUE TITLE
Feature Request: Ability to specify selector for update location

### ISSUE THREAD

**Issue by ChantryC** [claviska/jquery-minicolors#216]
I have implemented this myself already, but I have done so inelegantly enough that it is not worth contributing. 

I like the ability to be able to attach a color picker as part of an input, but some use cases require the value of the color to change an input not associated with the one in which the color picker is situated. My current setup allows me to choose the color inside a text input, but it updates a hidden input field rather than the text input itself. 

Maybe this would be worth including in a future change as an optional setting?

**Comment by claviska** [comment]
Why not use the change event to update the target input? You can listen for it in real time or set a delay to debounce it if necessary. What's the advantage of tying this into the lib?

**Comment by ChantryC** [comment]
I ended up going with a different library as it was not designed for my
purposes.

The issue is that it necessarily changes the value of the textbox, when
ideally it should be possible to capture the event and update elements on
the page as desired. In my case, I would have liked the hex code to be
updateable inside the color chooser as well, but that goes beyond the
intended scope of the library.

**Comment by claviska** [comment]
> The issue is that it necessarily changes the value of the textbox, when ideally it should be possible to capture the event and update elements on the page as desired.

The plugin does require a `text` or `hidden` input control to attach itself to, but you can absolutely capture the value of the control as it changes and send it over to other controls.

If you're looking to capture the raw click/drag/keydown event, I don't think that would be very helpful since the plugin needs to validate and normalize values as input is received. Otherwise, I'm not sure how we could make it more flexible.
