### ISSUE TITLE
Not working properly with arabic (RTL langs)

### ISSUE THREAD

**Issue by joshirohit100** [claviska/jquery-minicolors#246]
I am using Drupal.org/project/jQuery-minicolors module which integrates this library but on the arabic version, this doesn't work. Palette is not shown properly

**Comment by joshirohit100** [comment]
@sneetsher I am using this library in conjuction with this drupal module https://www.drupal.org/project/jquery_minicolors. Screen shot 
<img width="555" alt="screen shot 2018-04-10 at 11 17 32 am" src="https://user-images.githubusercontent.com/1336423/38538318-dacd3168-3cb0-11e8-88cc-d07545fb48d5.png"> In screenshot, my current language is arabic (RTL)

**Comment by claviska** [comment]
Not sure if this is just a stylesheet fix or if we need another RTL option. I have very little experience with RTL languages so I'm not sure what to expect, hence the _Help Wanted_ tag.

I appreciate any feedback and would especially love to see a PR that resolves this for Arabic and other RTL languages. 👍

**Comment by sneetsher** [comment]
There are multiple RTL support conventions, most used:
1. CSS file switch, separate files for LTR and RTL, only one active.
2. `dir="rtl"` in HTML, same CSS files for both.

As documented in [Drupal docs - CSS formatting guidelines](https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines).

AFAIK, 2nd is the best, it is more generic and may work well under other conventions. Used by Drupal v8.

@claviska , I have medium knowledge of HTML4/CSS2 and basic JS, I may able to fix it and submit a PR. It seems to me just CSS. Are you ok with the 2nd convention?

**Comment by claviska** [comment]
I'd be open to option 2, as I'd prefer to keep everything in the same stylesheet.

Does the minicolors control need to "inherit" the `dir` attribute, or should it be required on a parent element?

**Comment by joshirohit100** [comment]
This is how I solved -
`html[lang='ar'] .minicolors-slider {
     left: 0;
 }`

**Comment by sneetsher** [comment]
@claviska I pushed the commit for main styles. Few thing, I still need to look deeper or you may help me with:

-  I'm not sure about pickers,AFAIK they are relative and controlled in JS using coordinates from left/top. so no need to flip them?
- Bootstrap button group without RTL support (rounded corner on wrong side) , should I hack it here as there is no RTL from upstream  project?
-  There is something (may be in JS, didn't check it yet) that forces `minicolors-position-left` class. That breaks RTL default that should be `minicolors-position-right`. While debugging, I delete `minicolors-position-left` class in firefox developer tool, position fallback to CSS default, which looks good for me. So could we relay on CSS for default horizontal position?
- Hash sign in color codes sometimes to the left other times to the right.

**Comment by sneetsher** [comment]
@joshirohit100  please, if you could test the changes from the linked PR. Let me know about anything I miss and still need to be handled related to this issue.

**Comment by JoomliC** [comment]
Hi there,

Didn't have a look at minicolors since the time i worked on rgba, but here the screenshot of the color picker in Joomla 3 (where rtl is only managed by reversing position : https://github.com/joomla/joomla-cms/pull/10129/files#diff-c84005990b5f00eea2cc54b543c1fb22R183) : 
![capture d ecran 2018-04-14 a 01 54 20](https://user-images.githubusercontent.com/2385058/38761972-83ef75f2-3f87-11e8-9c72-bf9d5e3188d2.png)

So, don't know if it could help, but in Joomla, no changes needed for minicolors to work well with all languages. ;-)

Cyril

**Comment by sneetsher** [comment]
@JoomliC Thank you very much for the feedback.


Yeah, that seem easy and clean when elements positioning:

- all as default by browser 
- or all fixed with relative coordinates vs same component. (whatever: left/ right)
- no mixing between above methods in same group, and no forces positioning using `float`

This may was correct in v2.2.3 . That could be changed in v2.2.6  which break scale position in RTL.

In the related PR , I tried  to add full RTL support. I'm not an   expert  in UX,  but scale & grid order (from screenshot) is weird for an RTL user.

**Comment by claviska** [comment]
Linking the associated PR here: https://github.com/claviska/jquery-minicolors/pull/247

I got pretty sick this week and I'm about to move out of state so if other contributors could help test this out that would be awesome :)

I'm not ignoring this — just a rough couple of weeks for me!

**Comment by JoomliC** [comment]
I'm a bit busy this month, but i may be able to do advanced testing in May... ;-)

**Comment by sneetsher** [comment]
:) @claviska  & @JoomliC no problem.  Did you have chance to test it? I have some free time in these few weeks.

**Comment by claviska** [comment]
I haven't yet, sorry :(

**Comment by claviska** [comment]
This looks solid. Thanks for your work on this, @sneetsher! Merged in #247.
