### ISSUE TITLE
How to trigger minicolors change event manually

### ISSUE THREAD

**Issue by vivekmpuh** [claviska/jquery-minicolors#259]
Hi there, 

I want to trigger change event manually as I am passing the values dynamically like shown below 
`$('#elemid').minicolors('value', '#ff0000');`
above code modified to explain the problem, after this event I want to trigger the change event so as to update my object as well as the html (targeted element where the background color will change)

Thanks in advance

**Comment by claviska** [comment]
The `value` method calls `doChange`, which emits the change event if the value has actually changed.

If this isn’t the behavior you’re experiencing, it could be a bug. Please post a minimal test case so we can verify the issue is with the plugin and not elsewhere in your code.

Thanks!

**Comment by claviska** [comment]
Closing due to no response. Please post additional details if this is still an issue.

**Comment by arvindpdmn** [comment]
Commenting here since I believe this is related to my issue. I have an input text field of id `pcolor`. In JS, I change the value in this manner:
```
jQuery('#pcolor').val('#ffee00');
jQuery('#pcolor + .minicolors-swatch > span').css("background-color", '#ffee00');
```

However, this doesn't change the color selection in the Hue control palette and slider. Next, I tried to use the minicolors API. If I use `value()` as a method call, I get the error `TypeError: jQuery(...).minicolors.value is not a function`:
```
jQuery('#pcolor').minicolors.value('#ffee00');
```

I then tried to assign the value but the color selection doesn't change:
```
jQuery('#pcolor').minicolors.value = {color: '#ffee00'};
```

Thanks for your help.

![color](https://user-images.githubusercontent.com/5135463/79428963-89d61080-7fe4-11ea-8f77-fc9a7d517d73.jpg)

**Comment by claviska** [comment]
> jQuery('#pcolor').val('#ffee00');
jQuery('#pcolor + .minicolors-swatch > span').css("background-color", '#ffee00');

You should never try to set the value this way. Messing with internals will result in unreliable behavior. The correct syntax for setting the value [per the API](https://labs.abeautifulsite.net/jquery-minicolors/#methods) is:

```js
// Method 1
$('#pcolor').minicolors('value', '#fc0');

// Method 2
$('#pcolor').minicolors('value', { color: '#fc0', opacity: .5 });
```

**Comment by arvindpdmn** [comment]
That's awesome. Clean solution. Thanks.
