### ISSUE TITLE
Custom palette functionality request

### ISSUE THREAD

**Issue by Yapaslfeu** [claviska/jquery-minicolors#50]
Hi,
Your plugin is really the best i found on internet!
Just, could you add a custom palette functionality, to allow selection of preset colors?
(cf. Iris by Automattic plugin)
It would be really great!!
Thanks

**Comment by andri** [comment]
Not really a request but for a more simple color picker, a version that combines the brightness and saturation types would be great. I'm using this for a very simple CMS where the user can combine two colors to define a theme. Since the users have no predefined conceptions about how a color picker works or looks like, a picker that is more simple and just needs one click to select roughly any color would have superior UX for most user. Just a thought :)

**Comment by claviska** [comment]
Added in #186.
